MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 51 
  FASTER_RCNN: True
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 2x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.01
  GAMMA: 0.1
  # epoch_size = 30634
  MAX_ITER: 538541  # 17.58e 
  STEPS: [0, 414474, 497186]  # 13.53e, 16.23e
  WARM_UP_ITERS: 2084  # 0.068e
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 64
  WIDTH_PER_GROUP: 4
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  # md5sum of weights pkl file: aa14062280226e48f569ef1c7212e7c7
  WEIGHTS: 
  DATASETS: ('openimage_challenge_2018_train_hc_50', )
  SCALES: (400,600,800,1000,1200)
  MAX_SIZE: 1600 
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  SNAPSHOT_ITERS: 245000  # save every 30625 iters for 8 gpus
TEST:
  DATASETS: ('openimage_challenge_2018_validation_hc_50',)
  FORCE_JSON_DATASET_EVAL: True  # use coco eval
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: .
