MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet152_conv5_body
  NUM_CLASSES: 501 
  FASTER_RCNN: True
  # MASK_ON: True
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 1.44x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 2610000  # 12.17e
  STEPS: [0, 1740000, 2320000]    # 8.12e, 10.82e
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 32
  WIDTH_PER_GROUP: 8
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
# MRCNN:
#   ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs
#   RESOLUTION: 28  # (output mask resolution) default 14
#   ROI_XFORM_METHOD: RoIAlign
#   ROI_XFORM_RESOLUTION: 14  # default 7
#   ROI_XFORM_SAMPLING_RATIO: 2  # default 0
#   DILATION: 1  # default 2
#   CONV_INIT: MSRAFill  # default GaussianFill
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/25093814/X-152-32x8d-IN5k.pkl
  # DATASETS: ('openimage_challenge_2018_validation',)  # test memory
  DATASETS: ('openimage_challenge_2018_train_off', 'openimage_challenge_2018_train_ext')
  SCALES: (500, 600, 700, 800, 900, 1000, 1100)  # Scale jitter
  MAX_SIZE: 1500 
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  SNAPSHOT_ITERS: 860000  # save every 107500 iters for 8 gpus
TEST:
  DATASETS: ('openimage_challenge_2018_validation',)
  FORCE_JSON_DATASET_EVAL: True  # use coco eval
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.4
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.5
  RPN_PRE_NMS_TOP_N: 6000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000 
  # BBOX_AUG:
  #   ENABLED: True
  #   SCORE_HEUR: UNION
  #   COORD_HEUR: UNION
  #   H_FLIP: True
  #   SCALES: (400, 500, 600, 700, 900, 1000, 1100, 1200)
  #   MAX_SIZE: 2000
  #   SCALE_H_FLIP: True
  #   SCALE_SIZE_DEP: False
  #   ASPECT_RATIOS: ()
  #   ASPECT_RATIO_H_FLIP: False
  # MASK_AUG:
  #   ENABLED: True
  #   HEUR: SOFT_AVG
  #   H_FLIP: True
  #   SCALES: (400, 500, 600, 700, 900, 1000, 1100, 1200)
  #   MAX_SIZE: 2000
  #   SCALE_H_FLIP: True
  #   SCALE_SIZE_DEP: False
  #   ASPECT_RATIOS: ()
  #   ASPECT_RATIO_H_FLIP: False
OUTPUT_DIR: .
