MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 31 
  FASTER_RCNN: True
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  # epoch_size: 56921/8=7115.125 
  MAX_ITER: 347000   # 48.70e 
  STEPS: [0, 231000, 308000]  # 32.46e, 43.28e
  WARM_UP_ITERS: 500    # 0.068e
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: /workspace/blued/model/pretrained_model_detectron/R-101.pkl 
  DATASETS: ('blued_0920_train', 'qblued_20180803_train')
  SCALES: (500, 600, 700, 800, 900, 1000)
  MAX_SIZE: 2000 
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  SNAPSHOT_ITERS: 100000 # save every 12500 iters for 8 gpus
TEST:
  DATASETS: ('blued_0920_test',)
  FORCE_JSON_DATASET_EVAL: True
  SCALE: 800
  MAX_SIZE: 1600 
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: .
